name: Binpacking

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        cache-dependency-path: binpacking-visualization/package-lock.json
        node-version: 22.x
        cache: 'npm'
    - run: npm ci
      working-directory: binpacking-visualization
    - run: npm run build
      working-directory: binpacking-visualization
    - name: Deploy
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        command: pages deploy binpacking-visualization/dist --project-name binpacking
        wranglerVersion: '3'
