name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        architecture: [x64, arm64]

    steps:
    - uses: actions/checkout@v3

    - name: Install arm64 toolchain
      if: matrix.os == 'ubuntu-latest' && matrix.architecture == 'arm64'
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

    - name: Configure CMake
      shell: bash
      run: |
        mkdir build
        chmod +x ./configure_cmake.sh
        ./configure_cmake.sh ${{ matrix.os }} ${{ matrix.architecture }} -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -S .

    - name: Build
      run: cmake --build build --config Release
    
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-${{ matrix.architecture }}
        path: build